// Package schema contains database schema definitions
package schema

// CoreSchema returns the SQL statements for core tables
// Note: Main data tables (item_template, creature_template, quest_template, spell_template, gameobject_template)
// are now generated by GeneratedSchema() for 1:1 MySQL compatibility
func CoreSchema() string {
	return `
	-- Item Sets (still needed, not in MySQL 1:1)
	CREATE TABLE IF NOT EXISTS itemsets (
		itemset_id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		name_loc4 TEXT DEFAULT '',
		item1 INTEGER DEFAULT 0, item2 INTEGER DEFAULT 0, item3 INTEGER DEFAULT 0,
		item4 INTEGER DEFAULT 0, item5 INTEGER DEFAULT 0, item6 INTEGER DEFAULT 0,
		item7 INTEGER DEFAULT 0, item8 INTEGER DEFAULT 0, item9 INTEGER DEFAULT 0,
		item10 INTEGER DEFAULT 0,
		skill_id INTEGER DEFAULT 0,
		skill_level INTEGER DEFAULT 0,
		bonus1 INTEGER DEFAULT 0, bonus2 INTEGER DEFAULT 0, bonus3 INTEGER DEFAULT 0,
		bonus4 INTEGER DEFAULT 0, bonus5 INTEGER DEFAULT 0, bonus6 INTEGER DEFAULT 0,
		bonus7 INTEGER DEFAULT 0, bonus8 INTEGER DEFAULT 0,
		spell1 INTEGER DEFAULT 0, spell2 INTEGER DEFAULT 0, spell3 INTEGER DEFAULT 0,
		spell4 INTEGER DEFAULT 0, spell5 INTEGER DEFAULT 0, spell6 INTEGER DEFAULT 0,
		spell7 INTEGER DEFAULT 0, spell8 INTEGER DEFAULT 0
	);

	-- Quest Categories
	CREATE TABLE IF NOT EXISTS quest_categories (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Quest Category Groups
	CREATE TABLE IF NOT EXISTS quest_category_groups (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Quest Categories Enhanced
	CREATE TABLE IF NOT EXISTS quest_categories_enhanced (
		id INTEGER PRIMARY KEY,
		group_id INTEGER DEFAULT 0,
		name TEXT NOT NULL,            -- map-texture folder name (image key / identifier)
		display_name TEXT DEFAULT '',  -- official localized name (AreaTable.dbc)
		quest_count INTEGER DEFAULT 0
	);

	-- NPC Quest Start/End (Table names match MySQL)
	CREATE TABLE IF NOT EXISTS creature_questrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	CREATE TABLE IF NOT EXISTS creature_involvedrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	-- GameObject Quest Start/End
	CREATE TABLE IF NOT EXISTS gameobject_questrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	CREATE TABLE IF NOT EXISTS gameobject_involvedrelation (
		id INTEGER,
		quest INTEGER,
		PRIMARY KEY (id, quest)
	);

	-- Spell Durations
	CREATE TABLE IF NOT EXISTS spell_durations (
		id INTEGER PRIMARY KEY,
		duration_base INTEGER DEFAULT 0,
		duration_per_level INTEGER DEFAULT 0,
		max_duration INTEGER DEFAULT 0
	);

	-- Spell Range
	CREATE TABLE IF NOT EXISTS spell_range (
		id INTEGER PRIMARY KEY,
		range_min REAL DEFAULT 0,
		range_max REAL DEFAULT 0,
		name TEXT DEFAULT ''
	);

	-- Spell Radius
	CREATE TABLE IF NOT EXISTS spell_radius (
		id INTEGER PRIMARY KEY,
		radius_base REAL DEFAULT 0,
		radius_per_level REAL DEFAULT 0,
		radius_max REAL DEFAULT 0
	);

	-- Spell Cast Times
	CREATE TABLE IF NOT EXISTS spell_cast_times (
		id INTEGER PRIMARY KEY,
		base INTEGER DEFAULT 0,
		per_level INTEGER DEFAULT 0,
		minimum INTEGER DEFAULT 0
	);

	-- Spell Skill Categories
	CREATE TABLE IF NOT EXISTS spell_skill_categories (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Spell Skills
	CREATE TABLE IF NOT EXISTS spell_skills (
		id INTEGER PRIMARY KEY,
		category_id INTEGER DEFAULT 0,
		class_id INTEGER DEFAULT 0,
		name TEXT NOT NULL
	);

	-- Spell Skill Spells. req_skill_value is the minimum skill rank to use the
	-- spell (e.g. a recipe's required profession skill), from SkillLineAbility.dbc.
	-- min_value/max_value are the skill-up thresholds: below min the recipe is
	-- orange (always skills up), grey at max; yellow/green split at the midpoint
	-- (the server's SkillGainChance formula).
	CREATE TABLE IF NOT EXISTS spell_skill_spells (
		skill_id INTEGER,
		spell_id INTEGER,
		req_skill_value INTEGER DEFAULT 0,
		classmask INTEGER DEFAULT 0,
		min_value INTEGER DEFAULT 0,
		max_value INTEGER DEFAULT 0,
		PRIMARY KEY (skill_id, spell_id)
	);

	-- Spell Icons (maps spellIconId to icon file name)
	CREATE TABLE IF NOT EXISTS spell_icons (
		id INTEGER PRIMARY KEY,
		icon_name TEXT NOT NULL
	);

	-- Loot Tables (column names match MySQL)
	CREATE TABLE IF NOT EXISTS creature_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		-- Provenance, as on the spawn tables: 'official' is shipped baseline,
		-- 'local' is a drop table this user scraped from octowow. It survives an
		-- embedded-DB upgrade (see localMergeTables) and is promoted to
		-- 'official' at release time (cmd/promotedb).
		origin TEXT NOT NULL DEFAULT 'official',
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS reference_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS gameobject_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS item_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE TABLE IF NOT EXISTS disenchant_loot_template (
		entry INTEGER,
		item INTEGER,
		ChanceOrQuestChance REAL DEFAULT 0,
		groupid INTEGER DEFAULT 0,
		mincountOrRef INTEGER DEFAULT 1,
		maxcount INTEGER DEFAULT 1,
		PRIMARY KEY (entry, item)
	);

	CREATE INDEX IF NOT EXISTS idx_creature_loot_item ON creature_loot_template(item);
	CREATE INDEX IF NOT EXISTS idx_reference_loot_entry ON reference_loot_template(entry);

	-- Locks (for object requirements)
	CREATE TABLE IF NOT EXISTS locks (
		id INTEGER PRIMARY KEY,
		type1 INTEGER DEFAULT 0, type2 INTEGER DEFAULT 0, type3 INTEGER DEFAULT 0,
		type4 INTEGER DEFAULT 0, type5 INTEGER DEFAULT 0,
		prop1 INTEGER DEFAULT 0, prop2 INTEGER DEFAULT 0, prop3 INTEGER DEFAULT 0,
		prop4 INTEGER DEFAULT 0, prop5 INTEGER DEFAULT 0,
		req1 INTEGER DEFAULT 0, req2 INTEGER DEFAULT 0, req3 INTEGER DEFAULT 0,
		req4 INTEGER DEFAULT 0, req5 INTEGER DEFAULT 0
	);

	CREATE INDEX IF NOT EXISTS idx_gameobject_template_name ON gameobject_template(name);
	CREATE INDEX IF NOT EXISTS idx_gameobject_template_type ON gameobject_template(type);

	-- Random item suffixes ("of the Monkey"): ItemRandomProperties.dbc joined
	-- with the SpellItemEnchantment display text at client-import time. effects
	-- is a JSON array of lines like "+3 Agility".
	CREATE TABLE IF NOT EXISTS item_random_suffix (
		id INTEGER PRIMARY KEY,
		suffix TEXT NOT NULL,
		effects TEXT NOT NULL DEFAULT '[]'
	);

	-- Which suffixes an item can roll: item_template.random_property ->
	-- item_enchantment_template.entry; ench = item_random_suffix.id; chance is a
	-- relative weight. Imported from the MySQL world DB.
	CREATE TABLE IF NOT EXISTS item_enchantment_template (
		entry INTEGER NOT NULL,
		ench INTEGER NOT NULL,
		chance REAL DEFAULT 0,
		PRIMARY KEY (entry, ench)
	);

	-- Factions
	CREATE TABLE IF NOT EXISTS factions (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		description TEXT,
		name_loc4 TEXT DEFAULT '',
		description_loc4 TEXT DEFAULT '',
		side INTEGER DEFAULT 0,
		category_id INTEGER DEFAULT 0
	);

	CREATE INDEX IF NOT EXISTS idx_factions_name ON factions(name);

	-- Categories (for general categorization)
	CREATE TABLE IF NOT EXISTS categories (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		key TEXT UNIQUE NOT NULL,
		name TEXT NOT NULL,
		parent_id INTEGER,
		type TEXT,
		sort_order INTEGER DEFAULT 0
	);

	CREATE TABLE IF NOT EXISTS category_items (
		category_id INTEGER,
		item_id INTEGER,
		drop_rate TEXT,
		sort_order INTEGER DEFAULT 0,
		PRIMARY KEY (category_id, item_id)
	);

	-- Creature Metadata (Scraped info)
	CREATE TABLE IF NOT EXISTS creature_metadata (
		entry INTEGER PRIMARY KEY,
		map_url TEXT,
		infobox_json TEXT
	);

	-- Talent trees (one row per class tree) and talents (DBC-derived, populated
	-- from data/talents.json via the client-import flow).
	CREATE TABLE IF NOT EXISTS talent_tab (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		class TEXT NOT NULL,
		class_mask INTEGER DEFAULT 0,
		order_index INTEGER DEFAULT 0,
		background TEXT DEFAULT ''
	);

	CREATE TABLE IF NOT EXISTS talent (
		id INTEGER PRIMARY KEY,
		tab_id INTEGER NOT NULL,
		row INTEGER DEFAULT 0,
		col INTEGER DEFAULT 0,
		ranks TEXT DEFAULT '[]',   -- JSON array of per-rank spell ids
		req_talent INTEGER DEFAULT 0,
		req_rank INTEGER DEFAULT 0
	);
	CREATE INDEX IF NOT EXISTS idx_talent_tab_class ON talent_tab(class);
	CREATE INDEX IF NOT EXISTS idx_talent_tab_id ON talent(tab_id);

	-- Beast families (CreatureFamily.dbc), for the NPC Beast family sub-filter.
	CREATE TABLE IF NOT EXISTS creature_family (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Player classes (ChrClasses.dbc + FrameXML RAID_CLASS_COLORS):
	-- id -> display name, token, and UI color (#rrggbb).
	CREATE TABLE IF NOT EXISTS class_info (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		token TEXT DEFAULT '',
		color TEXT DEFAULT ''
	);

	-- Spell schools (FrameXML GlobalStrings.lua SPELL_SCHOOLn_CAP):
	-- school index -> localized display name. Colors are a client UI constant
	-- kept on the frontend; only the names follow the client's locale.
	CREATE TABLE IF NOT EXISTS spell_schools (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Spell proc data from the world DB (mangos). Column names mirror the MySQL
	-- tables so the importer can copy them 1:1. These give the real proc rate
	-- (PPM / custom %) that the DBC procChance field doesn't.
	CREATE TABLE IF NOT EXISTS spell_proc_event (
		entry INTEGER PRIMARY KEY,
		SchoolMask INTEGER DEFAULT 0,
		SpellFamilyName INTEGER DEFAULT 0,
		SpellFamilyMask0 INTEGER DEFAULT 0,
		SpellFamilyMask1 INTEGER DEFAULT 0,
		SpellFamilyMask2 INTEGER DEFAULT 0,
		procFlags INTEGER DEFAULT 0,
		procEx INTEGER DEFAULT 0,
		ppmRate REAL DEFAULT 0,
		CustomChance REAL DEFAULT 0,
		Cooldown INTEGER DEFAULT 0
	);
	-- Weapon-enchant proc rates (PPM), keyed by the proc spell id.
	CREATE TABLE IF NOT EXISTS spell_proc_item_enchant (
		entry INTEGER PRIMARY KEY,
		ppmRate REAL DEFAULT 0
	);
	-- Spell ids that are on-hit weapon-enchant procs (SpellItemEnchantment.dbc,
	-- type COMBAT_SPELL). Used to apply the engine's 1-PPM default when an enchant
	-- proc has no explicit rate in spell_proc_item_enchant.
	CREATE TABLE IF NOT EXISTS enchant_proc_spells (
		id INTEGER PRIMARY KEY
	);

	-- Spell mechanics (SpellMechanic.dbc): mechanic id -> name (e.g. "rooted").
	CREATE TABLE IF NOT EXISTS spell_mechanics (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);
	-- Spell dispel types (SpellDispelType.dbc): id -> name (e.g. "Magic").
	CREATE TABLE IF NOT EXISTS spell_dispel_types (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);
	-- Lock types (LockType.dbc): id -> name (Herbalism, Mining, Survival, ...).
	-- Drives the derived gathering/lock object categories.
	CREATE TABLE IF NOT EXISTS lock_types (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Item stat types (the ITEM_MOD enum): stat_type id -> display name. Seeded
	-- from the built-in canonical names, with the base stats overlaid from the
	-- client's GlobalStrings.lua (SPELL_STATn_NAME) so they follow its locale.
	-- The secondary/rating stats have no 1.12 client string and keep English.
	CREATE TABLE IF NOT EXISTS stat_types (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL
	);

	-- Playable races, assembled entirely from client data: ChrRaces.dbc (name,
	-- prefix, base language → faction), the glue character-create strings (flavor
	-- text), CharBaseInfo.dbc (available classes) and the racial skill lines.
	CREATE TABLE IF NOT EXISTS races (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL,
		file_string TEXT DEFAULT '',
		prefix TEXT DEFAULT '',
		faction TEXT DEFAULT '',
		info TEXT DEFAULT ''
	);
	-- Racial trait blurbs (the character-create ABILITY_INFO_ lines), ordered.
	CREATE TABLE IF NOT EXISTS race_abilities (
		race_id INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		text TEXT NOT NULL,
		PRIMARY KEY (race_id, idx)
	);
	-- Race → available class ids (CharBaseInfo.dbc).
	CREATE TABLE IF NOT EXISTS race_classes (
		race_id INTEGER NOT NULL,
		class_id INTEGER NOT NULL,
		PRIMARY KEY (race_id, class_id)
	);
	-- Race → racial spell ids (racial skill lines, by race bitmask).
	CREATE TABLE IF NOT EXISTS race_spells (
		race_id INTEGER NOT NULL,
		spell_id INTEGER NOT NULL,
		PRIMARY KEY (race_id, spell_id)
	);

	-- Flight (taxi) network, DBC-derived and projected onto continent maps.
	-- px/py are 0-100 percentages on the node's continent overview map.
	CREATE TABLE IF NOT EXISTS taxi_node (
		id INTEGER PRIMARY KEY,
		map_id INTEGER DEFAULT 0,
		continent TEXT DEFAULT '',  -- continent map image key (WorldMapArea area name)
		name TEXT NOT NULL,
		name_loc4 TEXT DEFAULT '',
		alliance INTEGER DEFAULT 0,
		horde INTEGER DEFAULT 0,
		px REAL DEFAULT 0,
		py REAL DEFAULT 0,
		world_x REAL DEFAULT 0,      -- node world coords, to match the flightmaster NPC
		world_y REAL DEFAULT 0,
		alliance_npc INTEGER DEFAULT 0, -- nearest Alliance flightmaster creature entry
		horde_npc INTEGER DEFAULT 0     -- nearest Horde flightmaster creature entry
	);
	CREATE TABLE IF NOT EXISTS taxi_path (
		id INTEGER PRIMARY KEY,
		from_node INTEGER NOT NULL,
		to_node INTEGER NOT NULL
	);
	CREATE TABLE IF NOT EXISTS taxi_path_node (
		path_id INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		px REAL DEFAULT 0,
		py REAL DEFAULT 0,
		PRIMARY KEY (path_id, idx)
	);
	CREATE INDEX IF NOT EXISTS idx_taxi_node_map ON taxi_node(map_id);
	CREATE INDEX IF NOT EXISTS idx_taxi_path_from ON taxi_path(from_node);

	-- Trainer spell lists (synced from MySQL). reqskill/reqskillvalue give the
	-- skill + rank you learn a spell at — the authoritative "Requires Skill (N)"
	-- for trainer-taught recipes (the learn-spell, not the craft spell).
	CREATE TABLE IF NOT EXISTS npc_trainer (
		entry INTEGER NOT NULL,
		spell INTEGER NOT NULL,
		spellcost INTEGER DEFAULT 0,
		reqskill INTEGER DEFAULT 0,
		reqskillvalue INTEGER DEFAULT 0,
		reqlevel INTEGER DEFAULT 0
	);
	CREATE INDEX IF NOT EXISTS idx_npc_trainer_spell ON npc_trainer(spell);
	-- Shared trainer lists referenced by creatures (negative npc_trainer.entry).
	CREATE TABLE IF NOT EXISTS npc_trainer_template (
		entry INTEGER NOT NULL,
		spell INTEGER NOT NULL,
		spellcost INTEGER DEFAULT 0,
		reqskill INTEGER DEFAULT 0,
		reqskillvalue INTEGER DEFAULT 0,
		reqlevel INTEGER DEFAULT 0
	);
	CREATE INDEX IF NOT EXISTS idx_npc_trainer_template_spell ON npc_trainer_template(spell);

	-- Maps a mount item to the mount spell it grants (Turtle's collection system;
	-- the "Add Mount to Collection" item-use teaches collection_mount.spellId).
	-- The mount spell's Mounted aura (78) carries the creature display id, so this
	-- bridges item -> renderable mount model.
	CREATE TABLE IF NOT EXISTS collection_mount (
		itemId INTEGER NOT NULL,
		spellId INTEGER NOT NULL,
		PRIMARY KEY (itemId, spellId)
	);
	CREATE INDEX IF NOT EXISTS idx_collection_mount_item ON collection_mount(itemId);

	-- Localized item type names from the client (ItemClass.dbc / ItemSubClass.dbc
	-- / GlobalStrings INVTYPE_*), so type/slot labels follow the client locale
	-- instead of built-in English. subclass name is the short form (Axe);
	-- verbose distinguishes 1H/2H (One-Handed Axes / Two-Handed Axes).
	CREATE TABLE IF NOT EXISTS item_class_names (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL DEFAULT ''
	);
	CREATE TABLE IF NOT EXISTS item_subclass_names (
		class INTEGER NOT NULL,
		subclass INTEGER NOT NULL,
		name TEXT NOT NULL DEFAULT '',
		verbose TEXT NOT NULL DEFAULT '',
		PRIMARY KEY (class, subclass)
	);
	CREATE TABLE IF NOT EXISTS inventory_type_names (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL DEFAULT ''
	);
	-- Localized creature type names (CreatureType.dbc): Beast, Undead, ...
	CREATE TABLE IF NOT EXISTS creature_type_names (
		id INTEGER PRIMARY KEY,
		name TEXT NOT NULL DEFAULT ''
	);
	-- Curated client UI strings (GlobalStrings.lua), key -> localized value, for
	-- the small name resolvers (item quality, bind type, spell-trigger prefix,
	-- creature rank).
	CREATE TABLE IF NOT EXISTS client_strings (
		key TEXT PRIMARY KEY,
		value TEXT NOT NULL DEFAULT ''
	);

	-- Boat/zeppelin transport routes (a->b hubs, possibly on different maps) and
	-- their projected track waypoints (per-map continent %).
	CREATE TABLE IF NOT EXISTS transport_route (
		id INTEGER PRIMARY KEY,
		type TEXT DEFAULT 'boat',  -- boat | zeppelin
		name_a TEXT, map_a INTEGER,
		name_b TEXT, map_b INTEGER
	);
	CREATE TABLE IF NOT EXISTS transport_waypoint (
		route_id INTEGER NOT NULL,
		idx INTEGER NOT NULL,
		map_id INTEGER DEFAULT 0,
		px REAL DEFAULT 0,
		py REAL DEFAULT 0,
		PRIMARY KEY (route_id, idx)
	);
	CREATE INDEX IF NOT EXISTS idx_transport_wp_route ON transport_waypoint(route_id);

	-- Indexes for 1:1 tables (created after GeneratedSchema)
	CREATE INDEX IF NOT EXISTS idx_item_template_name ON item_template(name);
	CREATE INDEX IF NOT EXISTS idx_item_template_class ON item_template(class);
	CREATE INDEX IF NOT EXISTS idx_item_template_quality ON item_template(quality);
	CREATE INDEX IF NOT EXISTS idx_item_template_display_id ON item_template(display_id);
	CREATE INDEX IF NOT EXISTS idx_creature_template_name ON creature_template(name);
	CREATE INDEX IF NOT EXISTS idx_quest_template_title ON quest_template(Title);
	CREATE INDEX IF NOT EXISTS idx_spell_template_name ON spell_template(name);
	CREATE INDEX IF NOT EXISTS idx_spell_template_icon_id ON spell_template(spellIconId);

	-- Aowow Zones (for coordinate conversion)
	CREATE TABLE IF NOT EXISTS aowow_zones (
		mapID INTEGER,
		zoneID INTEGER,
		name_loc0 TEXT,
		x_min REAL,
		x_max REAL,
		y_min REAL,
		y_max REAL,
		areatableID INTEGER,
		PRIMARY KEY (mapID, zoneID, x_min, x_max, y_min, y_max)
	);

	-- Creature Spawns (Synced from MySQL)
	-- origin: 'official' (from a published build / MySQL rebuild) or 'local'
	-- (the user's own scrapes). Local rows are never wiped by imports/rebuilds and
	-- are preserved across official DB upgrades unless the new official includes
	-- the same spawn. See data-distribution design (Stage 1).
	CREATE TABLE IF NOT EXISTS creature_spawn (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		creature_entry INTEGER,
		map_id INTEGER,
		zone_id INTEGER,
		zone_name TEXT,
		position_x REAL,
		position_y REAL,
		position_z REAL,
		origin TEXT NOT NULL DEFAULT 'official',
		UNIQUE(creature_entry, map_id, position_x, position_y)
	);
	CREATE INDEX IF NOT EXISTS idx_creature_spawn_entry ON creature_spawn(creature_entry);

	-- GameObject Spawns (Synced from MySQL)
	CREATE TABLE IF NOT EXISTS gameobject_spawn (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		gameobject_entry INTEGER,
		map_id INTEGER,
		zone_id INTEGER,
		zone_name TEXT,
		position_x REAL,
		position_y REAL,
		position_z REAL,
		origin TEXT NOT NULL DEFAULT 'official',
		UNIQUE(gameobject_entry, map_id, position_x, position_y)
	);
	CREATE INDEX IF NOT EXISTS idx_gameobject_spawn_entry ON gameobject_spawn(gameobject_entry);

	-- Trainer spell lists (which spells an NPC teaches), scraped from octowow NPC
	-- pages. Drives the NPC "Trains" section and the spell "Taught By" (reverse).
	CREATE TABLE IF NOT EXISTS npc_trainer_spell (
		npc_entry INTEGER,
		spell_id INTEGER,
		PRIMARY KEY (npc_entry, spell_id)
	);
	CREATE INDEX IF NOT EXISTS idx_npc_trainer_spell_spell ON npc_trainer_spell(spell_id);
	`
}
